# Generated by Django 5.1.1 on 2024-10-30 12:47

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('scooter', 'E-Scooter'), ('bike', 'E-Bike')], max_length=10)),
                ('city_name', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=100)),
                ('quantity_available', models.IntegerField(default=0)),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=5)),
                ('day_pass', models.DecimalField(decimal_places=2, default=7.99, max_digits=5)),
                ('monthly_subscription', models.DecimalField(decimal_places=2, default=28.99, max_digits=5)),
                ('annual_subscription', models.DecimalField(decimal_places=2, default=149.99, max_digits=6)),
                ('opening_time', models.TimeField(blank=True, default=datetime.time(8, 0), null=True)),
                ('closing_time', models.TimeField(blank=True, default=datetime.time(22, 0), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('city_name', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=100)),
                ('payment_plan', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.vehicle')),
            ],
        ),
    ]
