# Generated by Django 5.1.1 on 2024-10-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rental_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='quantity_available',
        ),
    ]
