# Generated by Django 5.1.1 on 2024-11-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location_lati',
            field=models.FloatField(default=55.86),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location_longi',
            field=models.FloatField(default=-4.25),
        ),
    ]
