# Generated by Django 5.1.1 on 2024-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_vehicle_is_available_vehicle_location_lati_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_level',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
